---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
  - name: dp-dd-job-creator-api

outputs:
  - name: target

run:
  path: dp-dd-job-creator-api/ci/scripts/build.sh
